machine:
    pre:
        - curl -sSL https://s3.amazonaws.com/circle-downloads/install-circleci-docker.sh | bash -s -- 1.10.0
    services:
        - docker

dependencies:
    override:
        - sudo pip install -U docker-compose

test:
    override:
        - docker-compose run -d --no-deps node1
        - cd node; mocha